
Caesar Naples Wiki Social Media Website
It is a story of a him and Her. 

A story that starts just like another one of those boy meets girl 

and the usual heartbreak that follows 

his love for her, it was so strong, even the universe stopped conspiring against them and let them be together.

In an alternate universe. . .

Me She Us and an Alternate Universe 
Romance Fantasy Novel

by Sourav Das


Links
Retail

Amazon

Social Media

Facebook

What has influenced your writing?
Love

What is your motivation for writing?
She

When did you start writing and what got you started?
August 2017 , my love for her

Do you have any upcoming writing goals?
Yes, will start my next novel in August 2018

What is your strong or weak point in your writing style?
It is my first novel, I intentionally did not give any names to my protagonist and co protagonist

Which writers do you admire?
Stephen King, Jeffrey Archer, Paulo Coelho

Copypasta Publishing
Made with the new Google Sites, an effortless way to create beautiful sites.	Create a siteReport abuse