"""empty message

Revision ID: 13e6699af3c9
Revises: d70a44d93b4d
Create Date: 2019-07-09 13:55:47.132649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e6699af3c9'
down_revision = 'd70a44d93b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redditpost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uri')
    )
    op.drop_constraint('chapter_uri_key', 'chapter', type_='unique')
    op.create_foreign_key(None, 'chapter', 'redditpost', ['uri'], ['uri'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapter', type_='foreignkey')
    op.create_unique_constraint('chapter_uri_key', 'chapter', ['uri'])
    op.drop_table('redditpost')
    # ### end Alembic commands ###
