"""empty message

Revision ID: 63a6b0893255
Revises: c647a24c5e35
Create Date: 2019-07-09 18:43:51.714550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a6b0893255'
down_revision = 'c647a24c5e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redditpost', sa.Column('reddit_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('redditpost', 'reddit_url')
    # ### end Alembic commands ###
