"""empty message

Revision ID: 66dc57ad5729
Revises: c483c0b2d64e
Create Date: 2019-07-09 23:04:28.339549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66dc57ad5729'
down_revision = 'c483c0b2d64e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
