"""empty message

Revision ID: 8210465f4dc6
Revises: 13e6699af3c9
Create Date: 2019-07-09 17:46:54.825724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8210465f4dc6'
down_revision = '13e6699af3c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redditpost', sa.Column('integer', sa.Integer(), nullable=True))
    op.add_column('redditpost', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'redditpost', 'user', ['username'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'redditpost', type_='foreignkey')
    op.drop_column('redditpost', 'username')
    op.drop_column('redditpost', 'integer')
    # ### end Alembic commands ###
