"""empty message

Revision ID: ae618914ecf1
Revises: c931faec869d
Create Date: 2019-06-20 00:22:26.035158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae618914ecf1'
down_revision = 'c931faec869d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_username_fkey', 'books', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('books_username_fkey', 'books', 'user', ['username'], ['username'])
    # ### end Alembic commands ###
