"""empty message

Revision ID: c647a24c5e35
Revises: 8210465f4dc6
Create Date: 2019-07-09 17:59:11.964350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c647a24c5e35'
down_revision = '8210465f4dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'chapter', 'user', ['username'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapter', type_='foreignkey')
    op.drop_column('chapter', 'username')
    # ### end Alembic commands ###
