"""empty message

Revision ID: d70a44d93b4d
Revises: 29b007db38fc
Create Date: 2019-07-08 17:32:31.988466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd70a44d93b4d'
down_revision = '29b007db38fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('uri', sa.String(), nullable=True))
    op.add_column('chapter', sa.Column('uri', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'chapter', ['uri'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapter', type_='unique')
    op.drop_column('chapter', 'uri')
    op.drop_column('books', 'uri')
    # ### end Alembic commands ###
