"""empty message

Revision ID: 4499a32bbdc0
Revises: 9185fb8b519b
Create Date: 2019-07-10 01:40:55.712363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4499a32bbdc0'
down_revision = '9185fb8b519b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subreddits', sa.Column('sub', sa.String(), nullable=True))
    op.drop_constraint('subreddits_subreddit_name_key', 'subreddits', type_='unique')
    op.create_unique_constraint(None, 'subreddits', ['sub'])
    op.drop_column('subreddits', 'subreddit_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subreddits', sa.Column('subreddit_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subreddits', type_='unique')
    op.create_unique_constraint('subreddits_subreddit_name_key', 'subreddits', ['subreddit_name'])
    op.drop_column('subreddits', 'sub')
    # ### end Alembic commands ###
