"""empty message

Revision ID: 9185fb8b519b
Revises: e71472cd7cdc
Create Date: 2019-07-10 01:39:09.929182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9185fb8b519b'
down_revision = 'e71472cd7cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subreddits', sa.Column('subreddit_name', sa.String(), nullable=True))
    op.drop_constraint('subreddits_name_key', 'subreddits', type_='unique')
    op.create_unique_constraint(None, 'subreddits', ['subreddit_name'])
    op.drop_column('subreddits', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subreddits', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subreddits', type_='unique')
    op.create_unique_constraint('subreddits_name_key', 'subreddits', ['name'])
    op.drop_column('subreddits', 'subreddit_name')
    # ### end Alembic commands ###
