"""empty message

Revision ID: c1daf9335a15
Revises: 4499a32bbdc0
Create Date: 2019-07-16 00:00:02.449712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1daf9335a15'
down_revision = '4499a32bbdc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chapter')
    op.add_column('redditpost', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'redditpost', 'books', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'redditpost', type_='foreignkey')
    op.drop_column('redditpost', 'parent_id')
    op.create_table('chapter',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uri', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['books.id'], name='chapter_parent_id_fkey'),
    sa.ForeignKeyConstraint(['uri'], ['redditpost.uri'], name='chapter_uri_fkey'),
    sa.ForeignKeyConstraint(['username'], ['user.username'], name='chapter_username_fkey'),
    sa.PrimaryKeyConstraint('id', name='chapter_pkey')
    )
    # ### end Alembic commands ###
