"""empty message

Revision ID: 16d77779ba4b
Revises: ae618914ecf1
Create Date: 2019-07-05 17:29:16.866604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16d77779ba4b'
down_revision = 'ae618914ecf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bots_client_id_key', 'bots', type_='unique')
    op.drop_constraint('bots_secret_key', 'bots', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('bots_secret_key', 'bots', ['secret'])
    op.create_unique_constraint('bots_client_id_key', 'bots', ['client_id'])
    # ### end Alembic commands ###
