"""empty message

Revision ID: 8f187da4147f
Revises: ddc909f3075b
Create Date: 2019-07-06 05:40:04.885061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f187da4147f'
down_revision = 'ddc909f3075b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('chapters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['books.id'], name='chapters_parent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chapters_pkey')
    )
    op.drop_table('chapter')
    # ### end Alembic commands ###
