"""empty message

Revision ID: 9910071070d0
Revises: 8f187da4147f
Create Date: 2019-07-07 17:27:51.854567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9910071070d0'
down_revision = '8f187da4147f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'books', 'user', ['username'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    # ### end Alembic commands ###
